language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

# Specify the operating systems on which to test for.
os:
  - linux

# command to install dependencies
install:
  - pip install --user pipenv
  - pipenv install

# command to run tests
script:
  - ./RaspberryCast.sh test
