version: 1
formatters:
  console:
    format: '%(name)s %(levelname)-5s: %(message)s'
  file:
    format: '%(asctime)s %(name)s %(levelname)-5s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: 'log/OpenCast.log'
    when: 'D'
    level: DEBUG
    backupCount: 5
    formatter: file
loggers:
  OpenCast:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  Downloader:
    level: INFO
    handlers: [file]
    propagate: no
